spring:
  application:
    name: ebookie
  config:
    import: env.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DB_DATABASE_NAME}?useUnicode=true&characterEncoding=utf8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  devtools:
    livereload:
      enabled: true  # 정적 리소스에 변화가 있을 때 바로 반영한다.
      restart: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: {GMAIL_ID}@gmail.com
    password: {GMAIL_APP_KEY}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000 # 1?
      refresh-token:
        expiration: 604800000 # 7?
  port-one:
    base-url: https://api.portone.io
    secret-key: ${PORT_ONE_SECRET_KEY}
    store-key: ${PORT_ONE_STORE_KEY}
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
server:
  port: 8080
app:
  upload:
#    img-dir: c:/dev/fs/ebookie/product_images/
#    file-dir: c:/dev/fs/ebookie/product-files/
    img-dir: D:/ebookie/product-images/
    file-dir: D:/ebookie/product-files/
