spring:
  application:
    name: ebookie
  config:
    import: env.properties
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/${DB_DATABASE_NAME}?useUnicode=true&characterEncoding=utf8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
#      ddl-auto: create-drop
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
#  sql:
#    init:
#      data-locations: classpath*:db/data.sql
#      mode: always
#      platform: mysql
  devtools:
    livereload:
      enabled: true  # 정적 리소스에 변화가 있을 때 바로 반영한다.
      restart: true
#  thymeleaf:
#    # 참조 경로
#    enabled: true
#    prefix: classpath:/templates/
#    suffix: .html
#    cache: false # thymeleaf에 대한 캐시를 남기지 않는다. cache=false 설정(운영시는 true)
#    check-template-location: true # templates 디렉토리에 파일이 있는지 없는지 체크, 없으면 에러를 발생시킨다.

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000 # 1?
      refresh-token:
        expiration: 604800000 # 7?
  port-one:
    base-url: https://api.portone.io
    secret-key: ${PORT_ONE_SECRET_KEY}
    store-key: ${PORT_ONE_STORE_KEY}
logging:
  level:
    org:
      hibernate:
        orm:
          jdbc:
            bind: trace
server:
  port: 8080

app:
  upload:
    img-dir: D:/ebookie/product-images/
    file-dir: D:/ebookie/product-files/